// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: api/user/user.proto

package user

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UserInterface_GetUserEmail_FullMethodName = "/clusterruntime.api.user.UserInterface/GetUserEmail"
)

// UserInterfaceClient is the client API for UserInterface service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserInterfaceClient interface {
	GetUserEmail(ctx context.Context, in *UserEmaileReq, opts ...grpc.CallOption) (*UserEmaileResponse, error)
}

type userInterfaceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserInterfaceClient(cc grpc.ClientConnInterface) UserInterfaceClient {
	return &userInterfaceClient{cc}
}

func (c *userInterfaceClient) GetUserEmail(ctx context.Context, in *UserEmaileReq, opts ...grpc.CallOption) (*UserEmaileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserEmaileResponse)
	err := c.cc.Invoke(ctx, UserInterface_GetUserEmail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserInterfaceServer is the server API for UserInterface service.
// All implementations must embed UnimplementedUserInterfaceServer
// for forward compatibility.
type UserInterfaceServer interface {
	GetUserEmail(context.Context, *UserEmaileReq) (*UserEmaileResponse, error)
	mustEmbedUnimplementedUserInterfaceServer()
}

// UnimplementedUserInterfaceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserInterfaceServer struct{}

func (UnimplementedUserInterfaceServer) GetUserEmail(context.Context, *UserEmaileReq) (*UserEmaileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserEmail not implemented")
}
func (UnimplementedUserInterfaceServer) mustEmbedUnimplementedUserInterfaceServer() {}
func (UnimplementedUserInterfaceServer) testEmbeddedByValue()                       {}

// UnsafeUserInterfaceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserInterfaceServer will
// result in compilation errors.
type UnsafeUserInterfaceServer interface {
	mustEmbedUnimplementedUserInterfaceServer()
}

func RegisterUserInterfaceServer(s grpc.ServiceRegistrar, srv UserInterfaceServer) {
	// If the following call pancis, it indicates UnimplementedUserInterfaceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UserInterface_ServiceDesc, srv)
}

func _UserInterface_GetUserEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserEmaileReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserInterfaceServer).GetUserEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserInterface_GetUserEmail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserInterfaceServer).GetUserEmail(ctx, req.(*UserEmaileReq))
	}
	return interceptor(ctx, in, info, handler)
}

// UserInterface_ServiceDesc is the grpc.ServiceDesc for UserInterface service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserInterface_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "clusterruntime.api.user.UserInterface",
	HandlerType: (*UserInterfaceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserEmail",
			Handler:    _UserInterface_GetUserEmail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/user/user.proto",
}
