server:
  name: "cluster-runtime"
  version: 0.0.1
  namespace: "cloud-copilot"
  grpc:
    network: "tcp"
    addr: 0.0.0.0:9003
    timeout: 15
log:
  max_size: 500
  max_backups: 3
  max_age: 28
app:
  - name: cilium
    version: "1.16.5"
    type: networking
  - name: base
    version: "1.24.2"
    type: networking
  - name: istiod
    version: "1.24.2"
    type: networking
  - name: cni
    version: "1.24.2"
    type: networking
  - name: ztunnel
    version: "1.24.2"
    type: networking
  - name: traefik
    version: "34.1.0"
    type: networking
  - name: argo-workflows
    version: "0.45.4"
    type: building
  - name: kube-prometheus-stack
    version: "69.1.1"
    type: monitoring
  - name: rook-ceph
    version: "v1.16.3"
    type: storage
  - name: cluster-autoscaler
    version: "9.46.0"
    type: scheduling
