server:
  name: "cluster-runtime"
  version: 0.0.1
  namespace: "cloud-copilot"
  grpc:
    network: "tcp"
    addr: 0.0.0.0:9003
    timeout: 15
log:
  max_size: 500
  max_backups: 3
  max_age: 28
app:
  - name: base
    version: "1.24.0"
    type: networking
  - name: istiod
    version: "1.24.0"
    type: networking
  - name: cni
    version: "1.24.0"
    type: networking
  - name: ztunnel
    version: "1.24.0"
    type: networking
  - name: gateway
    version: "1.24.0"
    type: networking
  - name: postgresql
    version: "15.1"
    type: database
  - name: argo-workflows
    version: "0.42.7"
    type: toolkit
  - name: cluster-autoscaler
    version: "9.43.2"
    type: toolkit
  - name: prometheus
    version: "25.30.1"
    type: monitoring
  - name: grafana
    version: "8.6.0"
    type: monitoring
  - name: rook-ceph
    version: "v1.15.5"
    type: storage
  - name: rook-ceph-cluster
    version: "v1.15.5"
    type: storage
