// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.1
// source: api/app/message.proto

package app

import (
	biz "github.com/f-rambo/cloud-copilot/cluster-runtime/internal/biz"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileUploadRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Icon     string `protobuf:"bytes,1,opt,name=icon,proto3" json:"icon,omitempty"`
	FileName string `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	Chunk    string `protobuf:"bytes,3,opt,name=chunk,proto3" json:"chunk,omitempty"`
	Resume   bool   `protobuf:"varint,4,opt,name=resume,proto3" json:"resume,omitempty"`
	Finish   bool   `protobuf:"varint,5,opt,name=finish,proto3" json:"finish,omitempty"`
}

func (x *FileUploadRequest) Reset() {
	*x = FileUploadRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_app_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileUploadRequest) ProtoMessage() {}

func (x *FileUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_app_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileUploadRequest.ProtoReflect.Descriptor instead.
func (*FileUploadRequest) Descriptor() ([]byte, []int) {
	return file_api_app_message_proto_rawDescGZIP(), []int{0}
}

func (x *FileUploadRequest) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *FileUploadRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *FileUploadRequest) GetChunk() string {
	if x != nil {
		return x.Chunk
	}
	return ""
}

func (x *FileUploadRequest) GetResume() bool {
	if x != nil {
		return x.Resume
	}
	return false
}

func (x *FileUploadRequest) GetFinish() bool {
	if x != nil {
		return x.Finish
	}
	return false
}

type CheckClusterResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok bool `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
}

func (x *CheckClusterResponse) Reset() {
	*x = CheckClusterResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_app_message_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckClusterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckClusterResponse) ProtoMessage() {}

func (x *CheckClusterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_app_message_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckClusterResponse.ProtoReflect.Descriptor instead.
func (*CheckClusterResponse) Descriptor() ([]byte, []int) {
	return file_api_app_message_proto_rawDescGZIP(), []int{1}
}

func (x *CheckClusterResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type InitResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Apps     []*biz.App        `protobuf:"bytes,1,rep,name=apps,proto3" json:"apps,omitempty"`
	Releases []*biz.AppRelease `protobuf:"bytes,2,rep,name=releases,proto3" json:"releases,omitempty"`
}

func (x *InitResponse) Reset() {
	*x = InitResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_app_message_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitResponse) ProtoMessage() {}

func (x *InitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_app_message_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitResponse.ProtoReflect.Descriptor instead.
func (*InitResponse) Descriptor() ([]byte, []int) {
	return file_api_app_message_proto_rawDescGZIP(), []int{2}
}

func (x *InitResponse) GetApps() []*biz.App {
	if x != nil {
		return x.Apps
	}
	return nil
}

func (x *InitResponse) GetReleases() []*biz.AppRelease {
	if x != nil {
		return x.Releases
	}
	return nil
}

type AppReleaseResourceItems struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Resources []*biz.AppReleaseResource `protobuf:"bytes,1,rep,name=resources,proto3" json:"resources,omitempty"`
}

func (x *AppReleaseResourceItems) Reset() {
	*x = AppReleaseResourceItems{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_app_message_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppReleaseResourceItems) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppReleaseResourceItems) ProtoMessage() {}

func (x *AppReleaseResourceItems) ProtoReflect() protoreflect.Message {
	mi := &file_api_app_message_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppReleaseResourceItems.ProtoReflect.Descriptor instead.
func (*AppReleaseResourceItems) Descriptor() ([]byte, []int) {
	return file_api_app_message_proto_rawDescGZIP(), []int{3}
}

func (x *AppReleaseResourceItems) GetResources() []*biz.AppReleaseResource {
	if x != nil {
		return x.Resources
	}
	return nil
}

type AppReleaseReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	App     *biz.App        `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
	Version *biz.AppVersion `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Release *biz.AppRelease `protobuf:"bytes,3,opt,name=release,proto3" json:"release,omitempty"`
	Repo    *biz.AppRepo    `protobuf:"bytes,4,opt,name=repo,proto3" json:"repo,omitempty"`
}

func (x *AppReleaseReq) Reset() {
	*x = AppReleaseReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_app_message_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppReleaseReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppReleaseReq) ProtoMessage() {}

func (x *AppReleaseReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_app_message_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppReleaseReq.ProtoReflect.Descriptor instead.
func (*AppReleaseReq) Descriptor() ([]byte, []int) {
	return file_api_app_message_proto_rawDescGZIP(), []int{4}
}

func (x *AppReleaseReq) GetApp() *biz.App {
	if x != nil {
		return x.App
	}
	return nil
}

func (x *AppReleaseReq) GetVersion() *biz.AppVersion {
	if x != nil {
		return x.Version
	}
	return nil
}

func (x *AppReleaseReq) GetRelease() *biz.AppRelease {
	if x != nil {
		return x.Release
	}
	return nil
}

func (x *AppReleaseReq) GetRepo() *biz.AppRepo {
	if x != nil {
		return x.Repo
	}
	return nil
}

type GetAppDetailByRepoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Repo    *biz.AppRepo `protobuf:"bytes,1,opt,name=repo,proto3" json:"repo,omitempty"`
	AppName string       `protobuf:"bytes,2,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
	Version string       `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *GetAppDetailByRepoReq) Reset() {
	*x = GetAppDetailByRepoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_app_message_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAppDetailByRepoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAppDetailByRepoReq) ProtoMessage() {}

func (x *GetAppDetailByRepoReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_app_message_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAppDetailByRepoReq.ProtoReflect.Descriptor instead.
func (*GetAppDetailByRepoReq) Descriptor() ([]byte, []int) {
	return file_api_app_message_proto_rawDescGZIP(), []int{5}
}

func (x *GetAppDetailByRepoReq) GetRepo() *biz.AppRepo {
	if x != nil {
		return x.Repo
	}
	return nil
}

func (x *GetAppDetailByRepoReq) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

func (x *GetAppDetailByRepoReq) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type AppItems struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Apps []*biz.App `protobuf:"bytes,1,rep,name=apps,proto3" json:"apps,omitempty"`
}

func (x *AppItems) Reset() {
	*x = AppItems{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_app_message_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppItems) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppItems) ProtoMessage() {}

func (x *AppItems) ProtoReflect() protoreflect.Message {
	mi := &file_api_app_message_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppItems.ProtoReflect.Descriptor instead.
func (*AppItems) Descriptor() ([]byte, []int) {
	return file_api_app_message_proto_rawDescGZIP(), []int{6}
}

func (x *AppItems) GetApps() []*biz.App {
	if x != nil {
		return x.Apps
	}
	return nil
}

type GetAppAndVersionInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	App     *biz.App        `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
	Version *biz.AppVersion `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *GetAppAndVersionInfo) Reset() {
	*x = GetAppAndVersionInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_app_message_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAppAndVersionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAppAndVersionInfo) ProtoMessage() {}

func (x *GetAppAndVersionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_app_message_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAppAndVersionInfo.ProtoReflect.Descriptor instead.
func (*GetAppAndVersionInfo) Descriptor() ([]byte, []int) {
	return file_api_app_message_proto_rawDescGZIP(), []int{7}
}

func (x *GetAppAndVersionInfo) GetApp() *biz.App {
	if x != nil {
		return x.App
	}
	return nil
}

func (x *GetAppAndVersionInfo) GetVersion() *biz.AppVersion {
	if x != nil {
		return x.Version
	}
	return nil
}

type DeleteAppVersionReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	App     *biz.App        `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
	Version *biz.AppVersion `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *DeleteAppVersionReq) Reset() {
	*x = DeleteAppVersionReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_app_message_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteAppVersionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAppVersionReq) ProtoMessage() {}

func (x *DeleteAppVersionReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_app_message_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAppVersionReq.ProtoReflect.Descriptor instead.
func (*DeleteAppVersionReq) Descriptor() ([]byte, []int) {
	return file_api_app_message_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteAppVersionReq) GetApp() *biz.App {
	if x != nil {
		return x.App
	}
	return nil
}

func (x *DeleteAppVersionReq) GetVersion() *biz.AppVersion {
	if x != nil {
		return x.Version
	}
	return nil
}

var File_api_app_message_proto protoreflect.FileDescriptor

var file_api_app_message_proto_rawDesc = []byte{
	0x0a, 0x15, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x70, 0x70, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x16, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72,
	0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x70, 0x70, 0x1a,
	0x16, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x62, 0x69, 0x7a, 0x2f, 0x61, 0x70,
	0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x8a, 0x01, 0x0a, 0x11, 0x46, 0x69, 0x6c, 0x65,
	0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x69, 0x63, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x69, 0x63, 0x6f,
	0x6e, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x63,
	0x68, 0x75, 0x6e, 0x6b, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x66, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x66, 0x69,
	0x6e, 0x69, 0x73, 0x68, 0x22, 0x26, 0x0a, 0x14, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x43, 0x6c, 0x75,
	0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02,
	0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x22, 0x61, 0x0a, 0x0c,
	0x49, 0x6e, 0x69, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x20, 0x0a, 0x04,
	0x61, 0x70, 0x70, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x62, 0x69, 0x7a,
	0x2e, 0x61, 0x70, 0x70, 0x2e, 0x41, 0x70, 0x70, 0x52, 0x04, 0x61, 0x70, 0x70, 0x73, 0x12, 0x2f,
	0x0a, 0x08, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x13, 0x2e, 0x62, 0x69, 0x7a, 0x2e, 0x61, 0x70, 0x70, 0x2e, 0x41, 0x70, 0x70, 0x52, 0x65,
	0x6c, 0x65, 0x61, 0x73, 0x65, 0x52, 0x08, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x73, 0x22,
	0x54, 0x0a, 0x17, 0x41, 0x70, 0x70, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x12, 0x39, 0x0a, 0x09, 0x72, 0x65,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e,
	0x62, 0x69, 0x7a, 0x2e, 0x61, 0x70, 0x70, 0x2e, 0x41, 0x70, 0x70, 0x52, 0x65, 0x6c, 0x65, 0x61,
	0x73, 0x65, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x09, 0x72, 0x65, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x73, 0x22, 0xb3, 0x01, 0x0a, 0x0d, 0x41, 0x70, 0x70, 0x52, 0x65, 0x6c,
	0x65, 0x61, 0x73, 0x65, 0x52, 0x65, 0x71, 0x12, 0x1e, 0x0a, 0x03, 0x61, 0x70, 0x70, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x62, 0x69, 0x7a, 0x2e, 0x61, 0x70, 0x70, 0x2e, 0x41,
	0x70, 0x70, 0x52, 0x03, 0x61, 0x70, 0x70, 0x12, 0x2d, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x62, 0x69, 0x7a, 0x2e, 0x61,
	0x70, 0x70, 0x2e, 0x41, 0x70, 0x70, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x07, 0x76,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x2d, 0x0a, 0x07, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x62, 0x69, 0x7a, 0x2e, 0x61, 0x70,
	0x70, 0x2e, 0x41, 0x70, 0x70, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x52, 0x07, 0x72, 0x65,
	0x6c, 0x65, 0x61, 0x73, 0x65, 0x12, 0x24, 0x0a, 0x04, 0x72, 0x65, 0x70, 0x6f, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x62, 0x69, 0x7a, 0x2e, 0x61, 0x70, 0x70, 0x2e, 0x41, 0x70,
	0x70, 0x52, 0x65, 0x70, 0x6f, 0x52, 0x04, 0x72, 0x65, 0x70, 0x6f, 0x22, 0x72, 0x0a, 0x15, 0x47,
	0x65, 0x74, 0x41, 0x70, 0x70, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x42, 0x79, 0x52, 0x65, 0x70,
	0x6f, 0x52, 0x65, 0x71, 0x12, 0x24, 0x0a, 0x04, 0x72, 0x65, 0x70, 0x6f, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x10, 0x2e, 0x62, 0x69, 0x7a, 0x2e, 0x61, 0x70, 0x70, 0x2e, 0x41, 0x70, 0x70,
	0x52, 0x65, 0x70, 0x6f, 0x52, 0x04, 0x72, 0x65, 0x70, 0x6f, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x70,
	0x70, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x70,
	0x70, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22,
	0x2c, 0x0a, 0x08, 0x41, 0x70, 0x70, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x12, 0x20, 0x0a, 0x04, 0x61,
	0x70, 0x70, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x62, 0x69, 0x7a, 0x2e,
	0x61, 0x70, 0x70, 0x2e, 0x41, 0x70, 0x70, 0x52, 0x04, 0x61, 0x70, 0x70, 0x73, 0x22, 0x65, 0x0a,
	0x14, 0x47, 0x65, 0x74, 0x41, 0x70, 0x70, 0x41, 0x6e, 0x64, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1e, 0x0a, 0x03, 0x61, 0x70, 0x70, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x62, 0x69, 0x7a, 0x2e, 0x61, 0x70, 0x70, 0x2e, 0x41, 0x70, 0x70,
	0x52, 0x03, 0x61, 0x70, 0x70, 0x12, 0x2d, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x62, 0x69, 0x7a, 0x2e, 0x61, 0x70, 0x70,
	0x2e, 0x41, 0x70, 0x70, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x07, 0x76, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x22, 0x64, 0x0a, 0x13, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x70,
	0x70, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x1e, 0x0a, 0x03, 0x61,
	0x70, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x62, 0x69, 0x7a, 0x2e, 0x61,
	0x70, 0x70, 0x2e, 0x41, 0x70, 0x70, 0x52, 0x03, 0x61, 0x70, 0x70, 0x12, 0x2d, 0x0a, 0x07, 0x76,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x62,
	0x69, 0x7a, 0x2e, 0x61, 0x70, 0x70, 0x2e, 0x41, 0x70, 0x70, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x42, 0x0a, 0x5a, 0x08, 0x61, 0x70,
	0x69, 0x2f, 0x61, 0x70, 0x70, 0x3b, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_app_message_proto_rawDescOnce sync.Once
	file_api_app_message_proto_rawDescData = file_api_app_message_proto_rawDesc
)

func file_api_app_message_proto_rawDescGZIP() []byte {
	file_api_app_message_proto_rawDescOnce.Do(func() {
		file_api_app_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_app_message_proto_rawDescData)
	})
	return file_api_app_message_proto_rawDescData
}

var file_api_app_message_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_api_app_message_proto_goTypes = []any{
	(*FileUploadRequest)(nil),       // 0: clusterruntime.api.app.FileUploadRequest
	(*CheckClusterResponse)(nil),    // 1: clusterruntime.api.app.CheckClusterResponse
	(*InitResponse)(nil),            // 2: clusterruntime.api.app.InitResponse
	(*AppReleaseResourceItems)(nil), // 3: clusterruntime.api.app.AppReleaseResourceItems
	(*AppReleaseReq)(nil),           // 4: clusterruntime.api.app.AppReleaseReq
	(*GetAppDetailByRepoReq)(nil),   // 5: clusterruntime.api.app.GetAppDetailByRepoReq
	(*AppItems)(nil),                // 6: clusterruntime.api.app.AppItems
	(*GetAppAndVersionInfo)(nil),    // 7: clusterruntime.api.app.GetAppAndVersionInfo
	(*DeleteAppVersionReq)(nil),     // 8: clusterruntime.api.app.DeleteAppVersionReq
	(*biz.App)(nil),                 // 9: biz.app.App
	(*biz.AppRelease)(nil),          // 10: biz.app.AppRelease
	(*biz.AppReleaseResource)(nil),  // 11: biz.app.AppReleaseResource
	(*biz.AppVersion)(nil),          // 12: biz.app.AppVersion
	(*biz.AppRepo)(nil),             // 13: biz.app.AppRepo
}
var file_api_app_message_proto_depIdxs = []int32{
	9,  // 0: clusterruntime.api.app.InitResponse.apps:type_name -> biz.app.App
	10, // 1: clusterruntime.api.app.InitResponse.releases:type_name -> biz.app.AppRelease
	11, // 2: clusterruntime.api.app.AppReleaseResourceItems.resources:type_name -> biz.app.AppReleaseResource
	9,  // 3: clusterruntime.api.app.AppReleaseReq.app:type_name -> biz.app.App
	12, // 4: clusterruntime.api.app.AppReleaseReq.version:type_name -> biz.app.AppVersion
	10, // 5: clusterruntime.api.app.AppReleaseReq.release:type_name -> biz.app.AppRelease
	13, // 6: clusterruntime.api.app.AppReleaseReq.repo:type_name -> biz.app.AppRepo
	13, // 7: clusterruntime.api.app.GetAppDetailByRepoReq.repo:type_name -> biz.app.AppRepo
	9,  // 8: clusterruntime.api.app.AppItems.apps:type_name -> biz.app.App
	9,  // 9: clusterruntime.api.app.GetAppAndVersionInfo.app:type_name -> biz.app.App
	12, // 10: clusterruntime.api.app.GetAppAndVersionInfo.version:type_name -> biz.app.AppVersion
	9,  // 11: clusterruntime.api.app.DeleteAppVersionReq.app:type_name -> biz.app.App
	12, // 12: clusterruntime.api.app.DeleteAppVersionReq.version:type_name -> biz.app.AppVersion
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_api_app_message_proto_init() }
func file_api_app_message_proto_init() {
	if File_api_app_message_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_app_message_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*FileUploadRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_app_message_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*CheckClusterResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_app_message_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*InitResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_app_message_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*AppReleaseResourceItems); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_app_message_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*AppReleaseReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_app_message_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*GetAppDetailByRepoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_app_message_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*AppItems); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_app_message_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*GetAppAndVersionInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_app_message_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteAppVersionReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_app_message_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_app_message_proto_goTypes,
		DependencyIndexes: file_api_app_message_proto_depIdxs,
		MessageInfos:      file_api_app_message_proto_msgTypes,
	}.Build()
	File_api_app_message_proto = out.File
	file_api_app_message_proto_rawDesc = nil
	file_api_app_message_proto_goTypes = nil
	file_api_app_message_proto_depIdxs = nil
}
